### ISSUE TITLE
S3::putObject(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by Zeryabfatima** [alyahmmed/CodeIgniter-S3-Upload#3]
i am having this issue for uploading files 
Severity: User Warning
Message:  S3::putObject(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
Filename: libraries/S3.php
Line Number: 424

**Comment by alyahmmed** [comment]
which S3 region did you use?

**Comment by ssaidurr** [comment]
> which S3 region did you use?

US East (Ohio) us-east-2
